import React from 'react'
import Script from 'next/script'
const page = () => {

    return (
        <div>
            <Script id='my-script'>
                {'alert("Welcome to About Page")'}
            </Script>
            This is About
        </div>
    )
}

export default page
export const metadata = {
    title: "Jayesh-Raect-About",
    description: "Generated by Jayesh",
};
