import Image from "next/image";

export default function Home() {
  return (
    <div className=" size-80 relative object-cover">
      <Image src="https://cdn.pixabay.com/photo/2015/04/23/22/00/new-year-background-736885_1280.jpg" fill={true} alt='Iamge' />
      This is body
    </div>
  );
}
export const metadata = {
  title: "Jayesh-Raect",
  description: "Generated by Jayesh",
};
