import React from 'react'

const page = () => {
    return (
        <div>
            This is resources page
        </div>
    )
}

export default page
export const metadata = {
    title: "Jayesh-Raect-resources",
    description: "Generated by Jayesh",
};
