import React from 'react'

const page = () => {
    return (
        <div>
            This is company page
        </div>
    )
}

export default page
export const metadata = {
    title: "Jayesh-Raect-company",
    description: "Generated by Jayesh",
};
